import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

// Signing comes from keystore.properties, which is gitignored and never committed. The
// release key is the app's identity: every APK on GitHub must be signed with it or
// installed apps cannot update - so it is created and backed up by a person, not
// generated by a build script that could quietly make a new one.
// -Pporthole.keystoreProps=PATH (relative to this project's root, or absolute) reads
// another properties file instead, so a second key signs without key files being copied
// around. Its storeFile resolves against the properties file's own directory.
val keystorePropsFile: File = rootProject.file(
    (project.findProperty("porthole.keystoreProps") as String?) ?: "keystore.properties"
).also {
    if (project.hasProperty("porthole.keystoreProps") && !it.exists()) error("porthole.keystoreProps: no such file: $it")
}
val keystoreProps = Properties().apply {
    if (keystorePropsFile.exists()) keystorePropsFile.inputStream().use { load(it) }
}

// Porthole updates itself from the project's GitHub releases. A build for a store must
// not (store policy: an app updates through the store), so a store bundle is made with
// -Pporthole.store=true and ships with the check compiled out.
val storeBuild = (project.findProperty("porthole.store") as String?) == "true"

android {
    namespace = "dev.shrimpscript.porthole"
    compileSdk = 36

    defaultConfig {
        applicationId = "dev.shrimpscript.porthole"
        minSdk = 29          // Android 10
        targetSdk = 36
        versionCode = 43
        versionName = "0.25.1"
        buildConfigField("String", "RELEASES_API", "\"https://api.github.com/repos/ShrimpScript/porthole/releases/latest\"")
        buildConfigField("String", "RELEASES_PAGE", "\"https://github.com/ShrimpScript/porthole/releases\"")
        buildConfigField("boolean", "SELF_UPDATE", (!storeBuild).toString())
    }

    signingConfigs {
        create("release") {
            if (keystoreProps.getProperty("storeFile") != null) {
                storeFile = keystorePropsFile.parentFile.resolve(keystoreProps.getProperty("storeFile"))
                storePassword = keystoreProps.getProperty("storePassword")
                keyAlias = keystoreProps.getProperty("keyAlias")
                keyPassword = keystoreProps.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        // Shrunk exactly like release, but debuggable, so it can be driven like a debug
        // build. R8 breaking sshj does not show up as a build error - it shows up as a
        // handshake that dies in the field - so the shrunk code has to be run, not just
        // inspected.
        create("minified") {
            initWith(getByName("debug"))
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            matchingFallbacks += listOf("debug")
        }

        release {
            // R8 with the sshj/BouncyCastle keep rules below. Shrinking matters here:
            // BouncyCastle alone is most of the APK.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            // Unsigned when there is no properties file, so a fresh clone still builds.
            signingConfig = if (keystoreProps.getProperty("storeFile") != null) {
                signingConfigs.getByName("release")
            } else {
                null
            }
        }
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            all { it.systemProperty("robolectric.graphicsMode", "NATIVE") }
        }
    }

    packaging {
        resources {
            // sshj and BouncyCastle both ship these; without the exclusion the APK fails
            // to package with a duplicate-resource error.
            excludes += setOf(
                "META-INF/DEPENDENCIES", "META-INF/LICENSE*", "META-INF/NOTICE*",
                "META-INF/INDEX.LIST", "META-INF/versions/9/OSGI-INF/MANIFEST.MF",
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin { jvmToolchain(17) }
    buildFeatures {
        compose = true
        buildConfig = true
    }

}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2025.06.00")
    implementation(composeBom)
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.material3:material3")
    // Vector icons for feed rows and controls. R8 keeps only the ones referenced.
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("androidx.core:core-ktx:1.17.0")
    implementation("androidx.browser:browser:1.8.0")
    implementation("androidx.glance:glance-appwidget:1.1.1")
    implementation("com.google.android.gms:play-services-code-scanner:16.1.0")
    // The system splash: the ring on the app's own ground from the first frame, instead
    // of a white flash before Compose draws.
    implementation("androidx.core:core-splashscreen:1.0.1")
    // The SSH failsafe. sshj's AuthNone works against the server config Tailscale SSH
    // uses (NoClientAuth), which is what makes "open terminal anyway" possible when the
    // daemon is down.
    implementation("com.hierynomus:sshj:0.39.0") {
        exclude(group = "org.bouncycastle")
    }
    implementation("org.bouncycastle:bcprov-jdk18on:1.79")
    implementation("org.bouncycastle:bcpkix-jdk18on:1.79")
    implementation("net.i2p.crypto:eddsa:0.3.0")
    debugImplementation("androidx.compose.ui:ui-tooling")
    // The terminal emulator is pure Kotlin, so it is tested on the JVM - VT parsing
    // bugs are exactly the kind only a test catches.
    testImplementation("junit:junit:4.13.2")
    // Screens rendered on the JVM: Robolectric's native graphics draws Compose to a
    // bitmap, so a screenshot of every screen exists without an emulator or a phone.
    testImplementation("org.robolectric:robolectric:4.17")
    testImplementation("androidx.test:core:1.7.0")
    testImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
}
