package session

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const askUseRec = `{"type":"assistant","message":{"model":"claude-fable-5-1","role":"assistant","content":[{"type":"tool_use","id":"toolu_01Q","name":"AskUserQuestion","input":{"questions":[{"question":"Which colour?","header":"Colour","options":[{"label":"Red"},{"label":"Blue"}]}]}}],"stop_reason":"tool_use"},"timestamp":"2026-09-14T06:05:30.000Z","cwd":"/srv/proj","sessionId":"fixture"}`
const askResultRec = `{"type":"user","message":{"role":"user","content":[{"tool_use_id":"toolu_01Q","type":"tool_result","content":"User answered Claude's questions"}]},"timestamp":"2026-09-14T06:05:41.000Z","cwd":"/srv/proj","sessionId":"fixture"}`
const promptRec = `{"type":"user","message":{"role":"user","content":"Ask me something."},"timestamp":"2026-09-14T06:05:22.208Z","cwd":"/srv/proj","sessionId":"fixture"}`

func TestPeekReportsTheQuestionWaiting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "s.jsonl")
	body := promptRec + "\n" + askUseRec + "\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	m, err := peek(path, int64(len(body)))
	if err != nil {
		t.Fatal(err)
	}
	if !m.Working || m.Asking != "Which colour?" {
		t.Fatalf("question up: working=%v asking=%q", m.Working, m.Asking)
	}
	body += askResultRec + "\n"
	_ = os.WriteFile(path, []byte(body), 0o600)
	m, _ = peek(path, int64(len(body)))
	if m.Asking != "" || !m.Working {
		t.Fatalf("answered, Claude continues: working=%v asking=%q", m.Working, m.Asking)
	}
}

// A local command (/model, /effort) writes three user records and gets no reply. Newer
// CLIs wrap the caveat in a tag; read as a prompt it opened a turn that never ended, and
// the session showed as working for days.
func TestALocalCommandIsNotATurn(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "s.jsonl")
	recs := []string{
		`{"type":"user","isMeta":true,"message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"},"timestamp":"2026-09-19T20:47:00.405Z","cwd":"/srv/proj","sessionId":"fixture"}`,
		`{"type":"user","message":{"role":"user","content":"<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args></command-args>"},"timestamp":"2026-09-19T20:47:00.405Z","cwd":"/srv/proj","sessionId":"fixture"}`,
		`{"type":"user","message":{"role":"user","content":"<local-command-stdout>Set model to Fable 5.1</local-command-stdout>"},"timestamp":"2026-09-19T20:47:00.407Z","cwd":"/srv/proj","sessionId":"fixture"}`,
		`{"type":"user","message":{"role":"user","content":"<bash-input>ls</bash-input>"},"timestamp":"2026-09-19T20:48:00.000Z","cwd":"/srv/proj","sessionId":"fixture"}`,
		`{"type":"user","message":{"role":"user","content":"<bash-stdout>a b c</bash-stdout><bash-stderr></bash-stderr>"},"timestamp":"2026-09-19T20:48:00.100Z","cwd":"/srv/proj","sessionId":"fixture"}`,
	}
	body := strings.Join(recs, "\n") + "\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	m, err := peek(path, int64(len(body)))
	if err != nil {
		t.Fatal(err)
	}
	if m.Working || !m.WorkingSince.IsZero() {
		t.Fatalf("local commands are not a turn: working=%v since=%v", m.Working, m.WorkingSince)
	}
}

func TestRegistryStatusOverrulesAStuckTurn(t *testing.T) {
	for status, want := range map[string]bool{"idle": true, "shell": true, "busy": false, "waiting": false, "": false} {
		if got := notWorking(status); got != want {
			t.Errorf("notWorking(%q) = %v, want %v", status, got, want)
		}
	}
}

// The clock is the turn's, not the latest tool call's.
func TestWorkingSinceIsWhenTheTurnBegan(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "s.jsonl")
	use := `{"type":"assistant","message":{"model":"claude-fable-5-1","role":"assistant","content":[{"type":"tool_use","id":"toolu_07","name":"Bash","input":{"command":"go test ./..."}}],"stop_reason":"tool_use"},"timestamp":"2026-09-14T06:06:00.000Z","cwd":"/srv/proj","sessionId":"fixture"}`
	result := `{"type":"user","message":{"role":"user","content":[{"tool_use_id":"toolu_07","type":"tool_result","content":"ok"}]},"timestamp":"2026-09-14T06:09:00.000Z","cwd":"/srv/proj","sessionId":"fixture"}`
	body := promptRec + "\n" + use + "\n" + result + "\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	m, err := peek(path, int64(len(body)))
	if err != nil {
		t.Fatal(err)
	}
	if !m.Working {
		t.Fatal("mid-turn after a tool result: should be working")
	}
	if got := m.WorkingSince.Format(time.RFC3339); got != "2026-09-14T06:05:22Z" {
		t.Fatalf("working since %s, want the prompt's 2026-09-14T06:05:22Z", got)
	}
}

// Text the CLI writes for itself is not a prompt in the list either: /context's table and a
// compaction's summary leave an idle session idle, and a manual /compact ends at its boundary.
func TestTheCLIsOwnTextDoesNotStartWork(t *testing.T) {
	end := `{"type":"assistant","message":{"model":"claude-fable-5-1","role":"assistant","content":[{"type":"text","text":"done"}],"stop_reason":"end_turn"},"timestamp":"2026-10-03T06:00:00.000Z","cwd":"/srv/proj","sessionId":"fixture"}`
	for name, tail := range map[string]string{
		"context table": `{"type":"user","isMeta":true,"message":{"role":"user","content":"## Context Usage\n\n**Tokens:** 27.1k / 1m (3%)"},"timestamp":"2026-10-03T06:01:00.000Z"}`,
		"compaction": `{"type":"user","message":{"role":"user","content":"/compact"},"timestamp":"2026-10-03T06:01:00.000Z"}` + "\n" +
			`{"type":"system","subtype":"compact_boundary","compactMetadata":{"trigger":"manual"},"timestamp":"2026-10-03T06:01:10.000Z"}` + "\n" +
			`{"type":"user","isCompactSummary":true,"message":{"role":"user","content":"This session is being continued from a previous conversation."},"timestamp":"2026-10-03T06:01:11.000Z"}`,
	} {
		path := filepath.Join(t.TempDir(), "s.jsonl")
		body := promptRec + "\n" + end + "\n" + tail + "\n"
		if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
		m, err := peek(path, int64(len(body)))
		if err != nil {
			t.Fatal(err)
		}
		if m.Working {
			t.Errorf("%s: reads as working", name)
		}
	}
}
