#!/usr/bin/env bash
# Print the Homebrew formula for a release, from its SHA256SUMS.
#
#   tools/homebrew-formula.sh 0.27.0 dist/0.27.0/SHA256SUMS > Formula/porthole.rb
#
# The formula installs the release's prebuilt daemon (macOS or Linux, Intel or ARM) as
# portholed, links porthole beside it, and depends on tmux. `portholed setup` is left to
# the person, as brew formulas do not start services or edit settings on their own.
set -euo pipefail
VERSION="${1:?version}"
SUMS="${2:?path to SHA256SUMS}"
BASE="${PORTHOLE_FORMULA_BASE:-https://github.com/ShrimpScript/porthole/releases/download/v$VERSION}"

sum() {
    local s
    s=$(awk -v f="$1" '$2 == f || $2 == "*" f { print $1 }' "$SUMS")
    [[ "$s" =~ ^[0-9a-f]{64}$ ]] || { echo "no checksum for $1 in $SUMS" >&2; exit 1; }
    echo "$s"
}

cat <<EOF
# Generated by tools/homebrew-formula.sh in github.com/ShrimpScript/porthole - edit it there.
class Porthole < Formula
  desc "Supervise Claude Code on this computer from your Android phone, over Tailscale"
  homepage "https://porthole-one.vercel.app"
  version "$VERSION"

  on_macos do
    on_arm do
      url "$BASE/portholed-darwin-arm64"
      sha256 "$(sum portholed-darwin-arm64)"
    end
    on_intel do
      url "$BASE/portholed-darwin-amd64"
      sha256 "$(sum portholed-darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/portholed-linux-arm64"
      sha256 "$(sum portholed-linux-arm64)"
    end
    on_intel do
      url "$BASE/portholed-linux-amd64"
      sha256 "$(sum portholed-linux-amd64)"
    end
  end

  depends_on "tmux"

  def install
    bin.install Dir["portholed-*"].first => "portholed"
    # Called as porthole, it starts Claude Code inside tmux, where the phone can reach it.
    bin.install_symlink "portholed" => "porthole"
  end

  def caveats
    <<~EOS
      Start the background service and add the approval hook to Claude Code:
        portholed setup
      Then check everything a phone needs, and pair one:
        portholed doctor
        portholed pair
      Start Claude Code with porthole instead of claude, in your project's folder.
    EOS
  end

  test do
    assert_match "portholed #{version}", shell_output("#{bin}/portholed version")
  end
end
EOF
